services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./archive:/archive
    ports:
      - '127.0.0.1:8001:80'
    environment:
      TZ: Asia/Tokyo
    restart: always
